### ISSUE TITLE
Decide on a repair procedure

### ISSUE THREAD

**Issue by dthigpen** [SharonLougheed/Equipment-Maintenance-in-VR#5]
Procedure requirements
- [x] Degree of complexity where user has to figure out how to go to about next task
- [x] Must have clearly defined steps or objectives
- [x] Requires some degree of realism when interacting with the model

**Comment by skystar1991** [comment]
We need some field research on these if we wanna be realistic and detail. Atos said we do not have to go in detail, so we can watch tons of youtube videos and use some common senses lol

**Comment by dthigpen** [comment]
@Truthseer27 Thanks for your incredible generator research!
